#!/usr/bin/env python3

from datetime import datetime, timezone
from hashlib import md5
from pprint import pprint
from json import dumps
from glob import glob

import os

FILENAME = list(set(glob("lineage-*")) - set(glob("*.json")))[0]
STATUS = FILENAME.split("-")[3]
VERSION = FILENAME.split("-")[1]
BUILD_TIME = int(datetime.now(timezone.utc).timestamp())

json_dict = {}
json_dict["response"] = []

ota_dict = {}

ota_dict["datetime"] = BUILD_TIME
ota_dict["filename"] = FILENAME

with open(FILENAME, "rb") as ROM_FILE:
    ota_dict["id"] = md5(ROM_FILE.read()).hexdigest()

ota_dict["romtype"] = STATUS
ota_dict["size"] = os.path.getsize(FILENAME)
ota_dict["url"] = f"https://thebiggestboi.skyblueborb.workers.dev/0:/{FILENAME}"
ota_dict["version"] = VERSION

json_dict["response"].append(ota_dict)

if "vanilla" in FILENAME:
    with open(f"lineage-{VERSION}-oss.json", "w", encoding="utf-8") as file:
        file.write(dumps(json_dict, indent=4))

else:
    with open(f"lineage-{VERSION}-oss-gms.json", "w", encoding="utf-8") as file:
        file.write(dumps(json_dict, indent=4))

pprint(json_dict)
